<a href="https://colab.research.google.com/github/hwarang97/Books/blob/main/hands_on_machine_learning_chapter3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [10]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

def identity_function(x):
  return x

In [8]:
def init_network(): # 관례적으로 가중치만 대문자로 쓰고, 그 외 변수는 모두 소문자로 작성
  network = {}
  network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
  network['b1'] = np.array([0.1, 0.2, 0.3])
  network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
  network['b2'] = np.array([0.1, 0.2])
  network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
  network['b3'] = np.array([0.1, 0.2])

  return network

def forward(network, x):
  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']

  a1 = np.dot(x, W1) + b1
  z1 = sigmoid(a1)
  a2 = np.dot(z1, W2) + b2
  z2 = sigmoid(a2)
  a3 = np.dot(z2, W3) + b3
  y = identity_function(a3)

  return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]


In [13]:
# 기존 소프트맥스
a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a)
print(exp_a)

sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [16]:
# 개선한 소프트맥스(분수는 위,아래에 같은 값을 곱하면 된다는 성질을 이용해 지수값의 크기를 줄임)
exp_a_2 = np.exp(a-2.9)
print(exp_a_2)

sum_exp_a_2 = np.sum(exp_a_2)
print(sum_exp_a_2)

y2 = exp_a_2 / sum_exp_a_2
print(y2)

[0.07427358 1.         3.00416602]
4.078439602160767
[0.01821127 0.24519181 0.73659691]
